### ISSUE TITLE
Wrong file needs to be hightlight on assignments

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#24]
In assignments, it would be nice if changed was marked for rats who are on the same file but the file they ran on yesterday was incorrect. 

For identifying these cases see commit 41763a574cd4b730bbc5cf25401f4651ba627a81

I don't have a test case yet, sorry.

**Comment by tofof** [comment]
This is difficult to do becasue assignments.xlsx is built from rat_archive which doesn't have access to the warnings in it. The only way to do this without having to deal with run_archive would be to read in the warnings from the .xlsx in `workbook_reader` and save the results to a column in rat_archive, but that means a new column in the permanent data store, just to store program state, which is bad practice.

Otherwise we have to read run_archive and filter to the most recent run per rat, which I guess is group_by and then arrange by date and then head? Seems clumsy. 

Better might be to just have Xiaopeng read the assignments directly and sidestep the need for this.

**Comment by nohelix** [comment]
Closed as this is better addressed with Xiaopeng's auto file picker based on assignments.
