### ISSUE TITLE
Rxn Graph fails for reds, blues

### ISSUE THREAD

**Issue by tofof** [Auerbach-Lab/Behavior-autoanalysis#45]
In my dataset, the RXN graph fails for reds and blues. It succeeds for GP, purple, and orange. Others (green? lp/rp?) are untested.

Please modify `Generate_Rxn_Graph()` to avoid failure, and/or create a `Generate_Second_Graph(row_added)` helper function that acts as an intermediary, calls the correct graph generation function, and returns the graph generated by that call.

See `Write_to_Archives()` at the bottom for an example of using `row_added` in this way, namely
` experiment = row_added$assignment %>% .[[1]] %>% pluck("experiment")` where pluck is the secret sauce to deal with the list of list difficulty with assignment.

**Comment by nohelix** [comment]
This is expected as the reds are on Gap Detection which should be Duration vs. Rxn rather than Frequency.

- [ ] Get graphing functions (ribbon vs range) coded independantly
- [ ] ID all the correct cases - e.g. 'ribbon' should work for Octave (phase = discrimination), Tones (non-oddball training)
- [ ] Integrate into shiny interface
